//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TJAStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TJAStudio.Properties.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   All Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Common Header に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommonHeader {
            get {
                return ResourceManager.GetString("CommonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dan Builder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DanBuilder {
            get {
                return ResourceManager.GetString("DanBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AioiLight に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Editor -  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Executable File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EXEExtensionDescripion {
            get {
                return ResourceManager.GetString("EXEExtensionDescripion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EXEExtensionName {
            get {
                return ResourceManager.GetString("EXEExtensionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TJAStudio Project File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExtensionDescription {
            get {
                return ResourceManager.GetString("ExtensionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .tsproj に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExtensionName {
            get {
                return ResourceManager.GetString("ExtensionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Header -  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TJAStudio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TITLE:The Sample M@ster
        ///#START
        ///0000,
        ///1000200010102000, // This is comment!
        ///1010201000304000,
        ///#GOGOSTART
        ///5000008060000080,
        ///7008000000000011,
        ///1,
        ///#END に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SampleText {
            get {
                return ResourceManager.GetString("SampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .tja File Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TJAExtensionDescription {
            get {
                return ResourceManager.GetString("TJAExtensionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .tja に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TJAExtensionName {
            get {
                return ResourceManager.GetString("TJAExtensionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UntitledProjectName {
            get {
                return ResourceManager.GetString("UntitledProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://aioilight.space/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
