//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TJAStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dialog() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TJAStudio.Properties.Dialog", typeof(Dialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Your course will be lost if you don&apos;t save. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DanMargeExit_Text {
            get {
                return ResourceManager.GetString("DanMargeExit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure to exit? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DanMargeExit_Title {
            get {
                return ResourceManager.GetString("DanMargeExit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel operation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HeaderDuplicated_Cancel {
            get {
                return ResourceManager.GetString("HeaderDuplicated_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Leave old header, and add new header に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HeaderDuplicated_Leave {
            get {
                return ResourceManager.GetString("HeaderDuplicated_Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove old header, and add new header に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HeaderDuplicated_Remove {
            get {
                return ResourceManager.GetString("HeaderDuplicated_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Old header: {0}
        ///New header: {1}
        ///
        ///Choose an action for duplicate header. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HeaderDuplicated_Text {
            get {
                return ResourceManager.GetString("HeaderDuplicated_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Header is duplicated に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HeaderDuplicated_Title {
            get {
                return ResourceManager.GetString("HeaderDuplicated_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This project {0} is not saved.
        ///Your changes will be lost when you don&apos;t save. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveChange_Text {
            get {
                return ResourceManager.GetString("SaveChange_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to save changes to {0}? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveChange_Title {
            get {
                return ResourceManager.GetString("SaveChange_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visit Website に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Version_Link {
            get {
                return ResourceManager.GetString("Version_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} Ver.{1}
        ///{0} was developed by {2}.
        ///{3}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Version_Text {
            get {
                return ResourceManager.GetString("Version_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Version_Title {
            get {
                return ResourceManager.GetString("Version_Title", resourceCulture);
            }
        }
    }
}
