//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TJAStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Simulator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Simulator() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TJAStudio.Properties.Simulator", typeof(Simulator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   TaikoDaijiro2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TaikoDaijiro2 {
            get {
                return ResourceManager.GetString("TaikoDaijiro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Taikojiro に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Taikojiro {
            get {
                return ResourceManager.GetString("Taikojiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Taikojiro2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Taikojiro2 {
            get {
                return ResourceManager.GetString("Taikojiro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TaikoWeb (Moded by Bui) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TaikoWeb_Bui {
            get {
                return ResourceManager.GetString("TaikoWeb_Bui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TJAPlayer2 forPC に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TJAPlayer2fPC {
            get {
                return ResourceManager.GetString("TJAPlayer2fPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TJAPlayer3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TJAPlayer3 {
            get {
                return ResourceManager.GetString("TJAPlayer3", resourceCulture);
            }
        }
    }
}
