//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TJAStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SystemMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemMessage() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TJAStudio.Properties.SystemMessage", typeof(SystemMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Do you want to save changes to {0}? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ApplicationExit {
            get {
                return ResourceManager.GetString("ApplicationExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cheking Directroy... {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CheckingDirectory {
            get {
                return ResourceManager.GetString("CheckingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cheking File... {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CheckingFile {
            get {
                return ResourceManager.GetString("CheckingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copied to clipboard. &quot;{0}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Copied {
            get {
                return ResourceManager.GetString("Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Measures: {0}
        ///Don (Small/Big/All/Raito): {1} / {2} / {3} / {4:0.00}%
        ///Ka  (Small/Big/All/Raito): {5} / {6} / {7} / {8:0.00}%
        ///Small / Big Notes Raito: {9:0.00}% / {10:0.00}%
        ///Max. Combo: {11}
        ///Play Time: {12}s に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CourseInfomation {
            get {
                return ResourceManager.GetString("CourseInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///
        ///
        ///Selection:
        ///Don (Small/Big/All/Raito): {0} / {1} / {2} / {3:0.00}%
        ///Ka  (Small/Big/All/Raito): {4} / {5} / {6} / {7:0.00}%
        ///Small / Big Notes Raito: {8:0.00}% / {9:0.00}%
        ///Time Span: {10}s に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CourseInfomation_Selection {
            get {
                return ResourceManager.GetString("CourseInfomation_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///
        ///
        ///This Measure: {0} / {1}
        ///Don (Small/Big/All/Raito): {2} / {3} / {4} / {5:0.00}%
        ///Ka  (Small/Big/All/Raito): {6} / {7} / {8} / {9:0.00}%
        ///Small / Big Notes Raito: {10:0.00}% / {11:0.00}%
        ///Resolution: {12}
        ///Time Span: {13}s に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CourseInfomation_ThisMeasure {
            get {
                return ResourceManager.GetString("CourseInfomation_ThisMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Course: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CourseInfomationTitle {
            get {
                return ResourceManager.GetString("CourseInfomationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cutted to clipboard. &quot;{0}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cutted {
            get {
                return ResourceManager.GetString("Cutted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The directory &quot;{0}&quot; could not be found.
        ///There is not enough directory to run the program.
        ///Please download the program again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This measure
        ///:{0}
        ///Without command:{1}
        ///Notes: {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DrawNotesPreview {
            get {
                return ResourceManager.GetString("DrawNotesPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duplicate header name.
        ///Delete previous header? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DuplicateHeader {
            get {
                return ResourceManager.GetString("DuplicateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This project {0} is not saved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditedWarning {
            get {
                return ResourceManager.GetString("EditedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file &quot;{0}&quot; could not be found.
        ///There is not enough file to run the program.
        ///Please download the program again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you use the value of the last 8 beats? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Measured_BPM {
            get {
                return ResourceManager.GetString("Measured_BPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the course name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MissedCourseName {
            get {
                return ResourceManager.GetString("MissedCourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the header name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MissedHeaderName {
            get {
                return ResourceManager.GetString("MissedHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line: {0}, Column: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NowCaret {
            get {
                return ResourceManager.GetString("NowCaret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenProject {
            get {
                return ResourceManager.GetString("OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Project File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenProjectFile {
            get {
                return ResourceManager.GetString("OpenProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Template に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenTemplate {
            get {
                return ResourceManager.GetString("OpenTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pasted from clipboard. &quot;{0}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Pasted {
            get {
                return ResourceManager.GetString("Pasted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveProject {
            get {
                return ResourceManager.GetString("SaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save .tja に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveTJA {
            get {
                return ResourceManager.GetString("SaveTJA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Measure: {0} / {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Status_Measure {
            get {
                return ResourceManager.GetString("Status_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} Ver.{1}
        ///{0} was developed by {2}.
        ///{3} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VersionDialog {
            get {
                return ResourceManager.GetString("VersionDialog", resourceCulture);
            }
        }
    }
}
